name: Build and Push Docker Image
on:
  push:
    branches:
      - main  # Replace with your main branch name, e.g., master if different.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  # Build context (root directory)
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/authfrontend:latest  # Replace with your Docker Hub username and repository name
